import Head from 'next/head'
import { Box, Flex, Text } from '@chakra-ui/react'
import Navbar from '@/components/navbar'
import HeroSection from '@/components/heroSection'
import AdvertSection from '@/components/advertSection'
import HowToOrderSection from '@/components/howToOrderSection'
import PopularFood from '@/components/popularFood'
import PopularCuisines from '@/components/popularCuisines'
import NearbyRestaurants from '@/components/nearbyRestaurants'
import WhySection from '@/components/whySection'
import Footer from '@/components/footer'
export default function Home() {
  return (
    <>
      <Head>
        <title>FoodBourg</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar/>
        <HeroSection/>
        <AdvertSection/>
        <HowToOrderSection/>
        <Text fontSize="3xl" px={10} fontWeight="bold" mb={5}>Popular Food in Your Area</Text>
        <Flex wrap="wrap" px={10} gap={5} justifyContent="space-between" mb={5}>
          <PopularFood/>
          <PopularFood/>
          <PopularFood/>
          <PopularFood/>
          <PopularFood/>
          <PopularFood/>
          <PopularFood/>
          <PopularFood/>
        </Flex>
        <Text fontSize="3xl" px={10} fontWeight="bold" mb={5}>Popular Cuisines</Text>
        <Flex wrap="wrap" px={10} gap={5} justifyContent="space-between" mb={10}>
          <PopularCuisines/>
          <PopularCuisines/>
          <PopularCuisines/>
          <PopularCuisines/>
          <PopularCuisines/>
          <PopularCuisines/>
          <PopularCuisines/>
          <PopularCuisines/>
          <PopularCuisines/>
          <PopularCuisines/>          
          <PopularCuisines/>
          <PopularCuisines/>
          <PopularCuisines/>
          <PopularCuisines/>
          <PopularCuisines/>
        </Flex>
        <Text fontSize="3xl" px={10} fontWeight="bold" mb={5}>Nearby Restaurants</Text>
        <Flex wrap="wrap" px={10} gap={5} justifyContent="space-between" mb={5}>
          <NearbyRestaurants/>
          <NearbyRestaurants/>
          <NearbyRestaurants/>
          <NearbyRestaurants/>
          <NearbyRestaurants/>
          <NearbyRestaurants/>
          <NearbyRestaurants/>
          <NearbyRestaurants/>
        </Flex>
        <WhySection/>
        <Footer/>
      </Box>
    </>
  )
}
