import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Box } from '@chakra-ui/react'
import Navbar from '@/components/navbar'
import HeroSection from '@/components/heroSection'
import AdvertSection from '@/components/advertSection'

export default function Home() {
  return (
    <>
      <Head>
        <title>FoodBourg</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar/>
        <HeroSection/>
        <AdvertSection/>
      </Box>
    </>
  )
}
